apiVersion: v1
kind: Secret
metadata:
  labels:
    app: petclinic
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: mysql
type: Opaque
data:
  database-name: cGV0Y2xpbmlj
  database-password: cGV0Y2xpbmlj
  database-root-password: cGV0Y2xpbmlj
  database-user: cGV0Y2xpbmlj
