apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-dev
bases:
  - ../../base/app
patchesJson6902:
- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: petclinic
  path: deploymentconfig-patch.yaml
